// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMacedo.Teste.Infra.SQLServerClient.SqlClient;

#nullable disable

namespace SMacedo.Teste.Infra.SQLServerClient.Migrations
{
    [DbContext(typeof(LeadsContext))]
    partial class LeadsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SMacedo.Teste.Domain.Entities.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeadStatus")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SMacedoTeste", "Leads");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Painters",
                            CreateDate = new DateTime(2022, 6, 13, 19, 29, 21, 104, DateTimeKind.Local).AddTicks(4900),
                            Description = "Need to paint 2 aluminum windows and a sliding glass door.",
                            Email = "jerod_schaefer50@yahoo.com",
                            FirstName = "Bill",
                            LastName = "Clapton",
                            LeadStatus = 0,
                            Phone = "8226375275",
                            Price = 62.0,
                            Suburb = "Yanderra 2574"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Painters",
                            CreateDate = new DateTime(2022, 6, 13, 19, 29, 21, 104, DateTimeKind.Local).AddTicks(4910),
                            Description = "internal walls 3 colors",
                            Email = "zoila3@hotmail.com",
                            FirstName = "Craig",
                            LastName = "List",
                            LeadStatus = 0,
                            Phone = "8226375275",
                            Price = 49.0,
                            Suburb = "Woolooware 2230"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Painters",
                            CreateDate = new DateTime(2022, 6, 13, 19, 29, 21, 104, DateTimeKind.Local).AddTicks(4912),
                            Description = "another teste to make colors",
                            Email = "annabel_moen@yahoo.com",
                            FirstName = "Savio",
                            LastName = "Teste",
                            LeadStatus = 0,
                            Phone = "8226375275",
                            Price = 600.5,
                            Suburb = "Nova Era 7890"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Painters",
                            CreateDate = new DateTime(2022, 6, 13, 19, 29, 21, 104, DateTimeKind.Local).AddTicks(4913),
                            Description = "Plaster exposed brick walls (see photos), square off 2 archways (see photos), and expand pantry (see photos)",
                            Email = "stephany92@gmail.com",
                            FirstName = "Pete",
                            LastName = "Parque",
                            LeadStatus = 1,
                            Phone = "8226375275",
                            Price = 26.0,
                            Suburb = "Carramar 6031"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
