// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMacedo.Teste.Infra.SQLServerClient.SqlClient;

#nullable disable

namespace SMacedo.Teste.Infra.SQLServerClient.Migrations
{
    [DbContext(typeof(LeadsContext))]
    [Migration("20220613191718_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SMacedo.Teste.Domain.Entities.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeadStatus")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SMacedoTeste", "Leads");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2022, 6, 13, 16, 17, 18, 388, DateTimeKind.Local).AddTicks(4606),
                            Description = "Need to paint 2 aluminum windows and a sliding glass door.",
                            FirstName = "Bill",
                            LastName = "Clapton",
                            LeadStatus = 0,
                            Price = 62.0,
                            Suburb = "Yanderra 2574"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2022, 6, 13, 16, 17, 18, 388, DateTimeKind.Local).AddTicks(4614),
                            Description = "internal walls 3 colors",
                            FirstName = "Craig",
                            LastName = "List",
                            LeadStatus = 0,
                            Price = 49.0,
                            Suburb = "Woolooware 2230"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2022, 6, 13, 16, 17, 18, 388, DateTimeKind.Local).AddTicks(4616),
                            Description = "another teste to make colors",
                            FirstName = "Savio",
                            LastName = "Teste",
                            LeadStatus = 0,
                            Price = 600.5,
                            Suburb = "Nova Era 7890"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
